CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  address TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'investor',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
